name: stack-the-letter

services:
  stack-the-letter-service:
    image: stack-the-letter-image:latest
    container_name: stack-the-letter
    restart: unless-stopped
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
        NPM_VERSION: ${NPM_VERSION}
    expose:
      - "3000"
    env_file:
      - .env
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - /etc/nginx/sites-available/westminster-abi.org:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
