services:
  story-tetris-service:
    image: story-tetris-image:latest  # Use the image built in the previous step
    container_name: story-tetris  # Name the container
    restart: unless-stopped  # Restart the container unless it was explicitly stopped
    build:
      context: .  # The build context is the current directory
      args:
        NODE_VERSION: ${NODE_VERSION}  # Pass NODE_VERSION from .env
        NPM_VERSION: ${NPM_VERSION}      # Pass NPM_VERSION from .env
    ports:
      - "3000:3000"  # Map port 3000 on the host to port 3000 in the container
    env_file:
      - .env # Use .env file for environment variables that are used inside the container
