// To change the grid layout dynamically,
// we need to explicitly map row and column indices
// to the corresponding tailwind grid classes.

export const gridCols = [
  "grid-cols-1",
  "grid-cols-2",
  "grid-cols-3",
  "grid-cols-4",
  "grid-cols-5",
  "grid-cols-6",
  "grid-cols-7",
  "grid-cols-8",
  "grid-cols-9",
  "grid-cols-10",
  "grid-cols-11",
  "grid-cols-12",
  "grid-cols-13",
  "grid-cols-14",
  "grid-cols-15",
  "grid-cols-16",
  "grid-cols-17",
  "grid-cols-18",
  "grid-cols-19",
  "grid-cols-20",
  "grid-cols-21",
  "grid-cols-22",
  "grid-cols-23",
  "grid-cols-24",
  "grid-cols-25",
  "grid-cols-26",
  "grid-cols-27",
  "grid-cols-28",
  "grid-cols-29",
  "grid-cols-30",
  "grid-cols-31",
  "grid-cols-32",
  "grid-cols-33",
  "grid-cols-34",
  "grid-cols-35",
  "grid-cols-36",
  "grid-cols-37",
  "grid-cols-38",
  "grid-cols-39",
  "grid-cols-40",
  "grid-cols-41",
  "grid-cols-42",
  "grid-cols-43",
  "grid-cols-44",
  "grid-cols-45",
  "grid-cols-46",
  "grid-cols-47",
  "grid-cols-48",
  "grid-cols-49",
  "grid-cols-50",
  "grid-cols-51",
  "grid-cols-52",
  "grid-cols-53",
  "grid-cols-54",
  "grid-cols-55",
  "grid-cols-56",
  "grid-cols-57",
  "grid-cols-58",
  "grid-cols-59",
  "grid-cols-60",
] as const;

export const gridRows = [
  "grid-rows-1",
  "grid-rows-2",
  "grid-rows-3",
  "grid-rows-4",
  "grid-rows-5",
  "grid-rows-6",
  "grid-rows-7",
  "grid-rows-8",
  "grid-rows-9",
  "grid-rows-10",
  "grid-rows-11",
  "grid-rows-12",
  "grid-rows-13",
  "grid-rows-14",
  "grid-rows-15",
  "grid-rows-16",
  "grid-rows-17",
  "grid-rows-18",
  "grid-rows-19",
  "grid-rows-20",
  "grid-rows-21",
  "grid-rows-22",
  "grid-rows-23",
  "grid-rows-24",
  "grid-rows-25",
] as const;
